default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: db #<%= ENV['POSTGRES_HOST'] %> #localhost

development:
  <<: *default
  database: medods-intern_development
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test: &TEST
  <<: *default
  database: medods-intern_test
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
